# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
  repositories:
    - repository: test_sh
      type: github
      endpoint: build1244
      name: build1244/test_sh
    - repository: az-devops
      type: github
      endpoint: build1244 (1)
      name: build1244/az-devops
# - repo: self


variables:
  tag: '$(Build.BuildId)'

stages:
# - stage: Build
#   displayName: Build image
#   jobs:  
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#         tags: |
#           $(tag)
- stage: Test
  displayName: Test
  jobs:
    - job: test
      displayName: test
      steps:
        - checkout: self
        - checkout: test_sh
        - checkout: az-devops
        - script: |
            pwd
            tree